export const AppString = {
    USERS_DOC: 'users',
    Poll_Doc: 'poll',
    PollAdmin_Col: 'pollAdmin',
    PollAdmin_Doc: 'adminAccess',
    QNA: 'qna2d',
    QNAREPLY: 'qna2dreply',
    QNAL1: 'qnal1',
    QNAREPLYL1: 'qnareplyl1',
    QNAL2: 'qnal2',
    QNAREPLYL2: 'qnareplyl2',
    QNAL3: 'qnal3',
    QNAREPLYL3: 'qnareplyl3',
    Poll_Doc1: 'poll1',
    PollAdmin_Col1: 'pollAdmin1',
    PollAdmin_Doc1: 'adminAccess',
    Poll_Doc2: 'poll2',
    PollAdmin_Col2: 'pollAdmin2',
    PollAdmin_Doc2: 'adminAccess',
    Poll_Doc3: 'poll3',
    PollAdmin_Col3: 'pollAdmin3',
    PollAdmin_Doc3: 'adminAccess',
}